# Generated by Django 3.2.7 on 2021-09-16 09:41

from django.db import migrations
import uuid


def copy_uuid_fields(apps, schema_editor):
    ImportBatch = apps.get_model('imports', 'ImportBatch')
    for batch in ImportBatch.objects.all():
        batch.id = uuid.UUID(batch.uid)
        batch.save()


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0005_alter_importbatch_uid'),
    ]

    operations = [
        migrations.RunPython(copy_uuid_fields, migrations.RunPython.noop)
    ]
