# Generated by Django 3.2.7 on 2021-09-16 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0007_auto_20210916_1152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='importbatch',
            old_name='id',
            new_name='uid',
        ),
    ]
