# Generated by Django 3.2.7 on 2021-09-16 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0008_rename_id_importbatch_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='import',
            name='batch2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='import_set_2', to='imports.importbatch', verbose_name='Batch2'),
        ),
    ]
