# Generated by Django 3.2.7 on 2021-09-16 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0010_copy_import_fks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='import',
            name='batch',
        ),
    ]
