# Generated by Django 3.2.7 on 2021-09-16 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0012_rename_batch2_import_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='import',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_set', to='imports.importbatch', verbose_name='Batch'),
        ),
    ]
