# Generated by Django 3.2.4 on 2021-06-30 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_send_behind_schedule_alert_mails'),
        ('default_documents', '0068_auto_20181214_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractordeliverablerevision',
            name='final_revision',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='Is final revision?'),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='response_required',
            field=models.BooleanField(blank=True, null=True, verbose_name='Response required'),
        ),
        migrations.AlterField(
            model_name='correspondencerevision',
            name='overdue',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='Overdue'),
        ),
        migrations.AlterField(
            model_name='correspondencerevision',
            name='under_review',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='Under Review'),
        ),
        migrations.AlterField(
            model_name='gtgmetadata',
            name='originator',
            field=models.ForeignKey(limit_choices_to={'type': 'originator'}, on_delete=django.db.models.deletion.PROTECT, to='accounts.entity', verbose_name='Originator'),
        ),
        migrations.AlterField(
            model_name='gtgmetadatarevision',
            name='final_revision',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='Is final revision?'),
        ),
        migrations.AlterField(
            model_name='minutesofmeeting',
            name='signed',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='Signed'),
        ),
    ]
