# Generated by Django 3.2.4 on 2021-07-02 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('default_documents', '0070_auto_20210701_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demometadatarevision',
            name='metadata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='default_documents.demometadata'),
        ),
    ]
