# Generated by Django 3.2.4 on 2021-07-02 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('default_documents', '0071_alter_demometadatarevision_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractordeliverable',
            name='latest_revision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='default_documents.contractordeliverablerevision', verbose_name='Latest revision'),
        ),
        migrations.AlterField(
            model_name='contractordeliverablerevision',
            name='metadata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='default_documents.contractordeliverable'),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='latest_revision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='default_documents.correspondencerevision', verbose_name='Latest revision'),
        ),
        migrations.AlterField(
            model_name='correspondencerevision',
            name='metadata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='default_documents.correspondence'),
        ),
        migrations.AlterField(
            model_name='demometadata',
            name='latest_revision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='default_documents.demometadatarevision', verbose_name='Latest revision'),
        ),
        migrations.AlterField(
            model_name='gtgmetadata',
            name='latest_revision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='default_documents.gtgmetadatarevision', verbose_name='Latest revision'),
        ),
        migrations.AlterField(
            model_name='gtgmetadatarevision',
            name='metadata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='default_documents.gtgmetadata'),
        ),
        migrations.AlterField(
            model_name='minutesofmeeting',
            name='latest_revision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='default_documents.minutesofmeetingrevision', verbose_name='Latest revision'),
        ),
        migrations.AlterField(
            model_name='minutesofmeetingrevision',
            name='metadata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='default_documents.minutesofmeeting'),
        ),
    ]
