# Generated by Django 3.2.4 on 2021-07-02 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_auto_20160607_1650'),
        ('reviews', '0021_auto_20160510_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.document', verbose_name='Document'),
        ),
    ]
