# Generated by Django 3.2.4 on 2021-06-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transmittals', '0058_set_due_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trsrevision',
            name='accepted',
            field=models.BooleanField(null=True, verbose_name='Accepted?'),
        ),
    ]
