# Generated by Django 3.2.4 on 2021-07-01 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_auto_20160607_1650'),
        ('transmittals', '0059_alter_trsrevision_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outgoingtransmittal',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='documents.document'),
        ),
        migrations.AlterField(
            model_name='transmittal',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='documents.document'),
        ),
    ]
