# Generated by Django 3.2.4 on 2021-06-30 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('audit_trail', '0003_auto_20160628_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='action_object_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_object', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='actor_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actor', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='target_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target', to='contenttypes.contenttype'),
        ),
    ]
