# Generated by Django 3.2.4 on 2021-06-30 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('distriblists', '0002_copy_lists_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributionlist',
            name='approver',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_external': False}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='related_lists_as_approver', to=settings.AUTH_USER_MODEL, verbose_name='Approver'),
        ),
        migrations.AlterField(
            model_name='distributionlist',
            name='leader',
            field=models.ForeignKey(limit_choices_to={'is_external': False}, on_delete=django.db.models.deletion.PROTECT, related_name='related_lists_as_leader', to=settings.AUTH_USER_MODEL, verbose_name='Leader'),
        ),
        migrations.AlterField(
            model_name='distributionlist',
            name='reviewers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_external': False}, related_name='related_lists_as_reviewer', to=settings.AUTH_USER_MODEL, verbose_name='Reviewers'),
        ),
    ]
