project_domain: phase.local
project_version: main
django_settings: core.settings.local
project_env: local
env_file: .env.local
env_target: ".env.local"
gunicorn_options: "--reload"
shell_prompt: PS1='\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
